// VERSION: 21739b4
// THIS FILE IS AUTOGENERATED - DO NOT EDIT
// Source: https://github.com/Software-Automation-Holdings-LLC/developer-common/blob/8d1fc342aa011694119f8ed188fe04e1b4790d56/configs/eslint.config.js

// ESLint flat config for ESLint 9.0.0+
// This replaces .eslintrc.json (legacy format)

import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        // Node globals
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
      },
    },
    rules: {
      indent: ["error", 2],
      "linebreak-style": ["error", "unix"],
      quotes: ["error", "double"],
      semi: ["error", "always"],
      "no-unused-vars": "warn",
      "no-console": "warn",
    },
    ignores: [
      "node_modules/**",
      "dist/**",
      "build/**",
      "vendor/**",
      "**/*.min.js",
    ],
  },
];
