// VERSION: c2f3d6b
// THIS FILE IS AUTOGENERATED - DO NOT EDIT
// Source: https://github.com/Software-Automation-Holdings-LLC/developer-common/blob/59f763fb17cfde530a83fa164fff5af2be5b081b/configs/eslint.config.mjs

// Project ESLint flat config (ESLint 9.0.0+)
// Imports the shared base and allows project-specific overrides.

import { base } from "./eslint.config.base.mjs";

export default [
  ...base,
  // Add project-specific overrides below
];
