// VERSION: ec1cd97
// THIS FILE IS AUTOGENERATED - DO NOT EDIT
// Source: https://github.com/Software-Automation-Holdings-LLC/developer-common/blob/59f763fb17cfde530a83fa164fff5af2be5b081b/configs/eslint.config.base.mjs

// ESLint flat config base for ESLint 9.0.0+
// Import and spread into your project's eslint.config.mjs:
//
//   import { base } from "./eslint.config.base.mjs";
//   export default [...base, { rules: { /* overrides */ } }];

import js from "@eslint/js";

export const base = [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        // Node globals
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
      },
    },
    rules: {
      indent: ["error", 2],
      "linebreak-style": ["error", "unix"],
      quotes: ["error", "double"],
      semi: ["error", "always"],
      "no-unused-vars": "warn",
      "no-console": "warn",
    },
    ignores: [
      "node_modules/**",
      "dist/**",
      "build/**",
      "vendor/**",
      "**/*.min.js",
    ],
  },
];

// Default export for direct use (backwards compatible)
export default base;
